# Generated by Django 5.2.7 on 2025-10-15 00:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_canasta', '0002_product_shoppinglist_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['-target_date', '-updated_at']},
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='title',
            field=models.CharField(default='Lista de compras', max_length=255),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='tu_canasta.user'),
        ),
    ]
